server:
  port: 7001


eureka:
  instance:
    hostname: localhost   #eureka服务端实列名称
  client:
      #false表示不向注册中心注册自己
    register-with-eureka: false
      #false表示自己端就是注册中心，我的职责就是维护服务实列，并不需要去检索服务
    fetch-register: false
    service-url:
        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      dafaultZone: http://${server.eureka.instance.hostname}:${server.port}/eureka/